name: Publish Docker
on:
  workflow_call:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 */7 * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ariaieboy/pg-restore-s3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
